import type { Metadata } from "next";
import Link from 'next/link'
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="NavBar">
            <Link href="/" className="NavButton">홈</Link>
            <Link href="/list" className="NavButton">리스트</Link>&nbsp;
            <Link href="/write" className="NavButton">글작성</Link>&nbsp;
            <Link href="/api/list" className="NavButton">리스트API</Link>&nbsp;
            <Link href="/register" className="NavButton">회원가입1</Link>
            <Link href="/sample/slug/a/1/2/3" className="NavButton">slug페이지</Link>
          </div>
        {children}
      </body>
    </html>
  );
}
